### ISSUE TITLE
[P0] Errors in Images in app docs and in HOL doc

### ISSUE THREAD

**Issue by CESARDELATORRE** [MSFT-SMT-ACCELERATORS/APC-Demo-App#83]
Errors in Images in app doc

https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/blob/main/docs/leaves-README.md

![image](https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/assets/1712635/a909f616-7d78-4ae9-b69d-0b7727185097)

**Comment by CESARDELATORRE** [comment]
Also IMAGES errors as well in the HOL:

<img width="749" alt="image" src="https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/assets/1712635/691f4cbd-6f7c-4110-82ff-408d0168e653">

**Comment by CESARDELATORRE** [comment]
Most Images in the HOL are broken, please fix:

<img width="771" alt="image" src="https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/assets/1712635/11d621ae-986c-46f2-a036-7e0f79398961">

**Comment by pabravil** [comment]
https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/commit/f7276921a318562e32fc09ebd62ca183bef38041
https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/commit/14d55d638bbe48b35b55749df6407211c58bd8e9
