### ISSUE TITLE
[P0] Link in HOL not right

### ISSUE THREAD

**Issue by CESARDELATORRE** [MSFT-SMT-ACCELERATORS/APC-Demo-App#85]
This link is not right:

https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/blob/main/docs/APC-HOL.md#apc-planned-operator-apis

<img width="743" alt="image" src="https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/assets/1712635/d0241885-f998-4993-b041-c86333db92f2">

It goes to the beginning of the HOL...

**Comment by pabravil** [comment]
https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/commit/5200f6090be5295e53ae8fc8166e43513e2114bb
