### ISSUE TITLE
[P0] Finish/fix all "TODO"

### ISSUE THREAD

**Issue by CESARDELATORRE** [MSFT-SMT-ACCELERATORS/APC-Demo-App#86]
Pending TODO:

https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/blob/main/docs/APC-HOL.md#sim-swap-detection

<img width="755" alt="image" src="https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/assets/1712635/987045d1-c1d3-4b1f-8013-1be31e55eab8">

**Comment by CESARDELATORRE** [comment]
Another pending TODO:

https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/blob/main/docs/APC-HOL.md#number-verification

<img width="792" alt="image" src="https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/assets/1712635/f67eda47-0362-4550-936a-98d1b3bf248b">

**Comment by CESARDELATORRE** [comment]
Search for TODO and "TO DO" in the repo. There are a few pending TODOs:

https://github.com/search?q=repo%3AMSFT-SMT-ACCELERATORS%2FAPC-Demo-App%20TODO&type=code

<img width="736" alt="image" src="https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/assets/1712635/d02b5ce1-b5eb-4b4d-bc7c-bbf9806bc6be">

Please, fix.

**Comment by pabravil** [comment]
Completed these in 

https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/commit/ee5990efb17e3093e231584396dcae95b5179d0b

https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/commit/0f92457c675aaec2af4dfd7807478dbe9e5d5c06

https://github.com/MSFT-SMT-ACCELERATORS/APC-Demo-App/commit/b36b24eb42acb32940816df4f5f9d38ce4335bf3
